site_name: VCFX Documentation
site_description: Documentation for the VCFX toolkit - a comprehensive VCF manipulation toolkit
site_author: VCFX Team
site_url: https://ieeta-pt.github.io/VCFX

# Repository
repo_name: ieeta-pt/VCFX
repo_url: https://github.com/ieeta-pt/VCFX
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 IEETA UA

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ieeta-pt/VCFX
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MiguelFSilva1
extra_css:
  - styles/custom.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Docker: docker.md
  - Tool Documentation: 
    - Overview: tools_overview.md
    - Data Analysis:
      - VCFX_allele_freq_calc: analysis/VCFX_allele_freq_calc.md
      - VCFX_variant_classifier: analysis/VCFX_variant_classifier.md
      - VCFX_inbreeding_calculator: analysis/VCFX_inbreeding_calculator.md
      - VCFX_dosage_calculator: analysis/VCFX_dosage_calculator.md
      - VCFX_hwe_tester: analysis/VCFX_hwe_tester.md
      - VCFX_distance_calculator: analysis/VCFX_distance_calculator.md
      - VCFX_allele_counter: analysis/VCFX_allele_counter.md
      - VCFX_allele_balance_calc: analysis/VCFX_allele_balance_calc.md
      - VCFX_variant_counter: analysis/VCFX_variant_counter.md
      - VCFX_ancestry_inferrer: analysis/VCFX_ancestry_inferrer.md
      - VCFX_ancestry_assigner: analysis/VCFX_ancestry_assigner.md
      - VCFX_ld_calculator: analysis/VCFX_ld_calculator.md
    - Data Filtering:
      - VCFX_phase_checker: filtering/VCFX_phase_checker.md
      - VCFX_phred_filter: filtering/VCFX_phred_filter.md
      - VCFX_record_filter: filtering/VCFX_record_filter.md
      - VCFX_gl_filter: filtering/VCFX_gl_filter.md
      - VCFX_allele_balance_filter: filtering/VCFX_allele_balance_filter.md
      - VCFX_population_filter: filtering/VCFX_population_filter.md
      - VCFX_probability_filter: filtering/VCFX_probability_filter.md
      - VCFX_nonref_filter: filtering/VCFX_nonref_filter.md
      - VCFX_impact_filter: filtering/VCFX_impact_filter.md
      - VCFX_phase_quality_filter: filtering/VCFX_phase_quality_filter.md
      - VCFX_region_subsampler: filtering/VCFX_region_subsampler.md
    - Data Transformation:
      - VCFX_multiallelic_splitter: transformation/VCFX_multiallelic_splitter.md
      - VCFX_sample_extractor: transformation/VCFX_sample_extractor.md
      - VCFX_position_subsetter: transformation/VCFX_position_subsetter.md
      - VCFX_format_converter: transformation/VCFX_format_converter.md
      - VCFX_genotype_query: transformation/VCFX_genotype_query.md
      - VCFX_indel_normalizer: transformation/VCFX_indel_normalizer.md
      - VCFX_sv_handler: transformation/VCFX_sv_handler.md
      - VCFX_fasta_converter: transformation/VCFX_fasta_converter.md
      - VCFX_sorter: transformation/VCFX_sorter.md
      - VCFX_af_subsetter: transformation/VCFX_af_subsetter.md
      - VCFX_reformatter: transformation/VCFX_reformatter.md
    - Quality Control:
      - VCFX_concordance_checker: quality-control/VCFX_concordance_checker.md
      - VCFX_missing_detector: quality-control/VCFX_missing_detector.md
      - VCFX_outlier_detector: quality-control/VCFX_outlier_detector.md
      - VCFX_alignment_checker: quality-control/VCFX_alignment_checker.md
      - VCFX_cross_sample_concordance: quality-control/VCFX_cross_sample_concordance.md
      - VCFX_validator: quality-control/VCFX_validator.md
    - File Management:
      - VCFX_indexer: file-management/VCFX_indexer.md
      - VCFX_file_splitter: file-management/VCFX_file_splitter.md
      - VCFX_compressor: file-management/VCFX_compressor.md
      - VCFX_diff_tool: file-management/VCFX_diff_tool.md
      - VCFX_subsampler: file-management/VCFX_subsampler.md
      - VCFX_duplicate_remover: file-management/VCFX_duplicate_remover.md
      - VCFX_merger: file-management/VCFX_merger.md
    - Annotation and Reporting:
      - VCFX_custom_annotator: annotation/VCFX_custom_annotator.md
      - VCFX_info_summarizer: annotation/VCFX_info_summarizer.md
      - VCFX_header_parser: annotation/VCFX_header_parser.md
      - VCFX_annotation_extractor: annotation/VCFX_annotation_extractor.md
      - VCFX_ref_comparator: annotation/VCFX_ref_comparator.md
      - VCFX_field_extractor: annotation/VCFX_field_extractor.md
      - VCFX_info_aggregator: annotation/VCFX_info_aggregator.md
      - VCFX_info_parser: annotation/VCFX_info_parser.md
      - VCFX_metadata_summarizer: annotation/VCFX_metadata_summarizer.md
    - Data Processing:
      - VCFX_missing_data_handler: processing/VCFX_missing_data_handler.md
      - VCFX_quality_adjuster: processing/VCFX_quality_adjuster.md
      - VCFX_haplotype_phaser: processing/VCFX_haplotype_phaser.md
      - VCFX_haplotype_extractor: processing/VCFX_haplotype_extractor.md
  - Python API: python_api.md
  - Contributing: CONTRIBUTING.md
  - Citation: citation.md
  - License: LICENSE.md
