[build-system]
requires = ["setuptools>=61", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "vcfx"
version = "1.0.2"
description = "Python bindings for the VCFX toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
