name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Check C/C++ formatting (informational)
        run: |
          echo "Checking C/C++ code formatting..."
          
          # Find all C/C++ files and check formatting
          FILES=$(find . -name "*.cpp" -o -name "*.c" -o -name "*.h" -o -name "*.hpp" | grep -v build | tr '\n' ' ')
          
          if [ -n "$FILES" ]; then
            echo "Files to check: $FILES"
            
            # Check if clang-format would make changes (dry-run)
            CHANGES=$(echo $FILES | xargs clang-format --style=file --dry-run --Werror 2>&1 || true)
            
            if [ -n "$CHANGES" ]; then
              echo "⚠️  C/C++ formatting issues found:"
              echo "$CHANGES"
              echo ""
              echo "To fix these issues locally, run:"
              echo "  ./scripts/format-code.sh"
              echo ""
              echo "Note: This is informational only and will not fail the build."
            else
              echo "✅ C/C++ code formatting looks good!"
            fi
          else
            echo "No C/C++ files found to check."
          fi
        continue-on-error: true

  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libz-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake zlib bash
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build
        shell: bash
      - name: Build
        run: cmake --build build --parallel
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        shell: bash
      - name: Check version consistency
        run: python scripts/check_version.py
        shell: bash

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
        shell: bash
      - name: Run Python tests
        run: pytest tests/python
        shell: bash

  python-wheels:
    needs: build-and-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libz-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake zlib bash
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          cmake -S . -B build -DPYTHON_BINDINGS=ON
          cmake --build build --parallel
          cmake --install build --prefix $PWD/install
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        shell: bash
      - name: Check version consistency
        run: python scripts/check_version.py
        shell: bash
      
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip wheel ./python -w dist
        shell: bash

      - name: Test Python wheel
        run: |
          python -m pip install dist/*.whl
          export PATH="$PWD/install/bin:$PATH"
          echo "$PWD/install/bin" >> $GITHUB_PATH
          cat <<'EOF' | python -
          import pathlib, vcfx, sys
          print('version:', vcfx.get_version())
          tools = vcfx.available_tools()
          print('tools:', len(tools))
          if tools:
              vcfx.run_tool(tools[0], '--help', check=False)
          p = pathlib.Path(vcfx.__file__).resolve().parent / 'py.typed'
          print('py.typed exists:', p.is_file())
          if not p.is_file():
              sys.exit('py.typed missing')
          EOF
        shell: bash
