name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags, same as docker-publish
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish_to:
        description: 'Publish to'
        required: true
        default: 'testpypi'
        type: choice
        options:
        - testpypi
        - pypi

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for version detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Extract version
      run: |
        # Extract version from CMakeLists.txt
        VERSION=$(grep -E "project\(VCFX VERSION" CMakeLists.txt | sed -E 's/.*VERSION ([0-9.]+).*/\1/')
        echo "VCFX_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Package version: $VERSION"
        
        # Create version file for Python package
        echo "$VERSION" > python/VERSION
    
    - name: Build package
      run: |
        cd python
        # Build only source distribution for now to avoid platform issues
        VCFX_VERSION=${{ env.VCFX_VERSION }} python -m build --sdist
        
        # List built files
        ls -la dist/
    
    - name: Check built package
      run: |
        cd python
        twine check dist/*
        # Verify version in package
        tar -tzf dist/*.tar.gz | head -20
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: python/dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to == 'testpypi' }}
    needs: [build]
    runs-on: ubuntu-latest
    
    environment:
      name: testpypi
      url: https://test.pypi.org/p/vcfx
    
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    if: ${{ github.event_name == 'release' || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to == 'pypi') }}
    needs: [build]
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/p/vcfx
    
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # If trusted publishing fails, you can use token instead:
      # Remove the permissions section above and uncomment below:
      # with:
      #   user: __token__
      #   password: ${{ secrets.PYPI_API_TOKEN }} 